<?php
/**
 * APIEntitiesMessagesOrderTranslation
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Swan API v4
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v4
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.43
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace Swagger\Client\Model;

use \ArrayAccess;
use \Swagger\Client\ObjectSerializer;

/**
 * APIEntitiesMessagesOrderTranslation Class Doc Comment
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class APIEntitiesMessagesOrderTranslation implements ModelInterface, ArrayAccess
{
    const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $swaggerModelName = 'API.Entities.Messages.OrderTranslation';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $swaggerTypes = [
        'id' => 'int',
        'order_id' => 'int',
        'recipient_name' => 'string',
        'recipient_postal_code' => 'string',
        'recipient_city' => 'string',
        'recipient_address' => 'string',
        'recipient_region' => 'string',
        'building_name' => 'string',
        'instructions' => 'string',
        'prefecture' => 'string',
        'prefecture_en' => 'string',
        'recipient_city_en' => 'string',
        'recipient_address_en' => 'string',
        'florist_country' => 'string',
        'florist_member_code' => 'string',
        'florist_location' => 'string',
        'florist_name' => 'string',
        'recipient_tele_home_part1' => 'string',
        'recipient_tele_home_part2' => 'string',
        'recipient_tele_home_part3' => 'string',
        'recipient_tele_work_part1' => 'string',
        'recipient_tele_work_part2' => 'string',
        'recipient_tele_work_part3' => 'string',
        'delivery_time_from' => 'string',
        'delivery_time_to' => 'string',
        'delivery_date_from' => '\DateTime',
        'delivery_date_to' => '\DateTime',
        'occasion' => 'string',
        'delivery' => 'string',
        'total_price' => 'double',
        'sender_name' => 'string',
        'sender_country' => 'string',
        'sender_post_code' => 'string',
        'sender_address' => 'string',
        'sender_city' => 'string',
        'sender_region' => 'string',
        'sender_phone_home' => 'string',
        'sender_phone_work' => 'string',
        'sender_phone_mobile' => 'string',
        'senderemail' => 'string'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $swaggerFormats = [
        'id' => 'int32',
        'order_id' => 'int32',
        'recipient_name' => null,
        'recipient_postal_code' => null,
        'recipient_city' => null,
        'recipient_address' => null,
        'recipient_region' => null,
        'building_name' => null,
        'instructions' => null,
        'prefecture' => null,
        'prefecture_en' => null,
        'recipient_city_en' => null,
        'recipient_address_en' => null,
        'florist_country' => null,
        'florist_member_code' => null,
        'florist_location' => null,
        'florist_name' => null,
        'recipient_tele_home_part1' => null,
        'recipient_tele_home_part2' => null,
        'recipient_tele_home_part3' => null,
        'recipient_tele_work_part1' => null,
        'recipient_tele_work_part2' => null,
        'recipient_tele_work_part3' => null,
        'delivery_time_from' => null,
        'delivery_time_to' => null,
        'delivery_date_from' => 'date-time',
        'delivery_date_to' => 'date-time',
        'occasion' => null,
        'delivery' => null,
        'total_price' => 'double',
        'sender_name' => null,
        'sender_country' => null,
        'sender_post_code' => null,
        'sender_address' => null,
        'sender_city' => null,
        'sender_region' => null,
        'sender_phone_home' => null,
        'sender_phone_work' => null,
        'sender_phone_mobile' => null,
        'senderemail' => null
    ];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function swaggerTypes()
    {
        return self::$swaggerTypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function swaggerFormats()
    {
        return self::$swaggerFormats;
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'id' => 'Id',
        'order_id' => 'OrderId',
        'recipient_name' => 'RecipientName',
        'recipient_postal_code' => 'RecipientPostalCode',
        'recipient_city' => 'RecipientCity',
        'recipient_address' => 'RecipientAddress',
        'recipient_region' => 'RecipientRegion',
        'building_name' => 'BuildingName',
        'instructions' => 'Instructions',
        'prefecture' => 'Prefecture',
        'prefecture_en' => 'Prefecture_en',
        'recipient_city_en' => 'RecipientCity_en',
        'recipient_address_en' => 'RecipientAddress_en',
        'florist_country' => 'FloristCountry',
        'florist_member_code' => 'FloristMemberCode',
        'florist_location' => 'FloristLocation',
        'florist_name' => 'FloristName',
        'recipient_tele_home_part1' => 'RecipientTeleHomePart1',
        'recipient_tele_home_part2' => 'RecipientTeleHomePart2',
        'recipient_tele_home_part3' => 'RecipientTeleHomePart3',
        'recipient_tele_work_part1' => 'RecipientTeleWorkPart1',
        'recipient_tele_work_part2' => 'RecipientTeleWorkPart2',
        'recipient_tele_work_part3' => 'RecipientTeleWorkPart3',
        'delivery_time_from' => 'DeliveryTimeFrom',
        'delivery_time_to' => 'DeliveryTimeTo',
        'delivery_date_from' => 'DeliveryDateFrom',
        'delivery_date_to' => 'DeliveryDateTo',
        'occasion' => 'Occasion',
        'delivery' => 'Delivery',
        'total_price' => 'TotalPrice',
        'sender_name' => 'SenderName',
        'sender_country' => 'SenderCountry',
        'sender_post_code' => 'SenderPostCode',
        'sender_address' => 'SenderAddress',
        'sender_city' => 'SenderCity',
        'sender_region' => 'SenderRegion',
        'sender_phone_home' => 'SenderPhoneHome',
        'sender_phone_work' => 'SenderPhoneWork',
        'sender_phone_mobile' => 'SenderPhoneMobile',
        'senderemail' => 'Senderemail'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'id' => 'setId',
        'order_id' => 'setOrderId',
        'recipient_name' => 'setRecipientName',
        'recipient_postal_code' => 'setRecipientPostalCode',
        'recipient_city' => 'setRecipientCity',
        'recipient_address' => 'setRecipientAddress',
        'recipient_region' => 'setRecipientRegion',
        'building_name' => 'setBuildingName',
        'instructions' => 'setInstructions',
        'prefecture' => 'setPrefecture',
        'prefecture_en' => 'setPrefectureEn',
        'recipient_city_en' => 'setRecipientCityEn',
        'recipient_address_en' => 'setRecipientAddressEn',
        'florist_country' => 'setFloristCountry',
        'florist_member_code' => 'setFloristMemberCode',
        'florist_location' => 'setFloristLocation',
        'florist_name' => 'setFloristName',
        'recipient_tele_home_part1' => 'setRecipientTeleHomePart1',
        'recipient_tele_home_part2' => 'setRecipientTeleHomePart2',
        'recipient_tele_home_part3' => 'setRecipientTeleHomePart3',
        'recipient_tele_work_part1' => 'setRecipientTeleWorkPart1',
        'recipient_tele_work_part2' => 'setRecipientTeleWorkPart2',
        'recipient_tele_work_part3' => 'setRecipientTeleWorkPart3',
        'delivery_time_from' => 'setDeliveryTimeFrom',
        'delivery_time_to' => 'setDeliveryTimeTo',
        'delivery_date_from' => 'setDeliveryDateFrom',
        'delivery_date_to' => 'setDeliveryDateTo',
        'occasion' => 'setOccasion',
        'delivery' => 'setDelivery',
        'total_price' => 'setTotalPrice',
        'sender_name' => 'setSenderName',
        'sender_country' => 'setSenderCountry',
        'sender_post_code' => 'setSenderPostCode',
        'sender_address' => 'setSenderAddress',
        'sender_city' => 'setSenderCity',
        'sender_region' => 'setSenderRegion',
        'sender_phone_home' => 'setSenderPhoneHome',
        'sender_phone_work' => 'setSenderPhoneWork',
        'sender_phone_mobile' => 'setSenderPhoneMobile',
        'senderemail' => 'setSenderemail'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'id' => 'getId',
        'order_id' => 'getOrderId',
        'recipient_name' => 'getRecipientName',
        'recipient_postal_code' => 'getRecipientPostalCode',
        'recipient_city' => 'getRecipientCity',
        'recipient_address' => 'getRecipientAddress',
        'recipient_region' => 'getRecipientRegion',
        'building_name' => 'getBuildingName',
        'instructions' => 'getInstructions',
        'prefecture' => 'getPrefecture',
        'prefecture_en' => 'getPrefectureEn',
        'recipient_city_en' => 'getRecipientCityEn',
        'recipient_address_en' => 'getRecipientAddressEn',
        'florist_country' => 'getFloristCountry',
        'florist_member_code' => 'getFloristMemberCode',
        'florist_location' => 'getFloristLocation',
        'florist_name' => 'getFloristName',
        'recipient_tele_home_part1' => 'getRecipientTeleHomePart1',
        'recipient_tele_home_part2' => 'getRecipientTeleHomePart2',
        'recipient_tele_home_part3' => 'getRecipientTeleHomePart3',
        'recipient_tele_work_part1' => 'getRecipientTeleWorkPart1',
        'recipient_tele_work_part2' => 'getRecipientTeleWorkPart2',
        'recipient_tele_work_part3' => 'getRecipientTeleWorkPart3',
        'delivery_time_from' => 'getDeliveryTimeFrom',
        'delivery_time_to' => 'getDeliveryTimeTo',
        'delivery_date_from' => 'getDeliveryDateFrom',
        'delivery_date_to' => 'getDeliveryDateTo',
        'occasion' => 'getOccasion',
        'delivery' => 'getDelivery',
        'total_price' => 'getTotalPrice',
        'sender_name' => 'getSenderName',
        'sender_country' => 'getSenderCountry',
        'sender_post_code' => 'getSenderPostCode',
        'sender_address' => 'getSenderAddress',
        'sender_city' => 'getSenderCity',
        'sender_region' => 'getSenderRegion',
        'sender_phone_home' => 'getSenderPhoneHome',
        'sender_phone_work' => 'getSenderPhoneWork',
        'sender_phone_mobile' => 'getSenderPhoneMobile',
        'senderemail' => 'getSenderemail'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$swaggerModelName;
    }

    

    

    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->container['id'] = isset($data['id']) ? $data['id'] : null;
        $this->container['order_id'] = isset($data['order_id']) ? $data['order_id'] : null;
        $this->container['recipient_name'] = isset($data['recipient_name']) ? $data['recipient_name'] : null;
        $this->container['recipient_postal_code'] = isset($data['recipient_postal_code']) ? $data['recipient_postal_code'] : null;
        $this->container['recipient_city'] = isset($data['recipient_city']) ? $data['recipient_city'] : null;
        $this->container['recipient_address'] = isset($data['recipient_address']) ? $data['recipient_address'] : null;
        $this->container['recipient_region'] = isset($data['recipient_region']) ? $data['recipient_region'] : null;
        $this->container['building_name'] = isset($data['building_name']) ? $data['building_name'] : null;
        $this->container['instructions'] = isset($data['instructions']) ? $data['instructions'] : null;
        $this->container['prefecture'] = isset($data['prefecture']) ? $data['prefecture'] : null;
        $this->container['prefecture_en'] = isset($data['prefecture_en']) ? $data['prefecture_en'] : null;
        $this->container['recipient_city_en'] = isset($data['recipient_city_en']) ? $data['recipient_city_en'] : null;
        $this->container['recipient_address_en'] = isset($data['recipient_address_en']) ? $data['recipient_address_en'] : null;
        $this->container['florist_country'] = isset($data['florist_country']) ? $data['florist_country'] : null;
        $this->container['florist_member_code'] = isset($data['florist_member_code']) ? $data['florist_member_code'] : null;
        $this->container['florist_location'] = isset($data['florist_location']) ? $data['florist_location'] : null;
        $this->container['florist_name'] = isset($data['florist_name']) ? $data['florist_name'] : null;
        $this->container['recipient_tele_home_part1'] = isset($data['recipient_tele_home_part1']) ? $data['recipient_tele_home_part1'] : null;
        $this->container['recipient_tele_home_part2'] = isset($data['recipient_tele_home_part2']) ? $data['recipient_tele_home_part2'] : null;
        $this->container['recipient_tele_home_part3'] = isset($data['recipient_tele_home_part3']) ? $data['recipient_tele_home_part3'] : null;
        $this->container['recipient_tele_work_part1'] = isset($data['recipient_tele_work_part1']) ? $data['recipient_tele_work_part1'] : null;
        $this->container['recipient_tele_work_part2'] = isset($data['recipient_tele_work_part2']) ? $data['recipient_tele_work_part2'] : null;
        $this->container['recipient_tele_work_part3'] = isset($data['recipient_tele_work_part3']) ? $data['recipient_tele_work_part3'] : null;
        $this->container['delivery_time_from'] = isset($data['delivery_time_from']) ? $data['delivery_time_from'] : null;
        $this->container['delivery_time_to'] = isset($data['delivery_time_to']) ? $data['delivery_time_to'] : null;
        $this->container['delivery_date_from'] = isset($data['delivery_date_from']) ? $data['delivery_date_from'] : null;
        $this->container['delivery_date_to'] = isset($data['delivery_date_to']) ? $data['delivery_date_to'] : null;
        $this->container['occasion'] = isset($data['occasion']) ? $data['occasion'] : null;
        $this->container['delivery'] = isset($data['delivery']) ? $data['delivery'] : null;
        $this->container['total_price'] = isset($data['total_price']) ? $data['total_price'] : null;
        $this->container['sender_name'] = isset($data['sender_name']) ? $data['sender_name'] : null;
        $this->container['sender_country'] = isset($data['sender_country']) ? $data['sender_country'] : null;
        $this->container['sender_post_code'] = isset($data['sender_post_code']) ? $data['sender_post_code'] : null;
        $this->container['sender_address'] = isset($data['sender_address']) ? $data['sender_address'] : null;
        $this->container['sender_city'] = isset($data['sender_city']) ? $data['sender_city'] : null;
        $this->container['sender_region'] = isset($data['sender_region']) ? $data['sender_region'] : null;
        $this->container['sender_phone_home'] = isset($data['sender_phone_home']) ? $data['sender_phone_home'] : null;
        $this->container['sender_phone_work'] = isset($data['sender_phone_work']) ? $data['sender_phone_work'] : null;
        $this->container['sender_phone_mobile'] = isset($data['sender_phone_mobile']) ? $data['sender_phone_mobile'] : null;
        $this->container['senderemail'] = isset($data['senderemail']) ? $data['senderemail'] : null;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets id
     *
     * @return int
     */
    public function getId()
    {
        return $this->container['id'];
    }

    /**
     * Sets id
     *
     * @param int $id id
     *
     * @return $this
     */
    public function setId($id)
    {
        $this->container['id'] = $id;

        return $this;
    }

    /**
     * Gets order_id
     *
     * @return int
     */
    public function getOrderId()
    {
        return $this->container['order_id'];
    }

    /**
     * Sets order_id
     *
     * @param int $order_id order_id
     *
     * @return $this
     */
    public function setOrderId($order_id)
    {
        $this->container['order_id'] = $order_id;

        return $this;
    }

    /**
     * Gets recipient_name
     *
     * @return string
     */
    public function getRecipientName()
    {
        return $this->container['recipient_name'];
    }

    /**
     * Sets recipient_name
     *
     * @param string $recipient_name recipient_name
     *
     * @return $this
     */
    public function setRecipientName($recipient_name)
    {
        $this->container['recipient_name'] = $recipient_name;

        return $this;
    }

    /**
     * Gets recipient_postal_code
     *
     * @return string
     */
    public function getRecipientPostalCode()
    {
        return $this->container['recipient_postal_code'];
    }

    /**
     * Sets recipient_postal_code
     *
     * @param string $recipient_postal_code recipient_postal_code
     *
     * @return $this
     */
    public function setRecipientPostalCode($recipient_postal_code)
    {
        $this->container['recipient_postal_code'] = $recipient_postal_code;

        return $this;
    }

    /**
     * Gets recipient_city
     *
     * @return string
     */
    public function getRecipientCity()
    {
        return $this->container['recipient_city'];
    }

    /**
     * Sets recipient_city
     *
     * @param string $recipient_city recipient_city
     *
     * @return $this
     */
    public function setRecipientCity($recipient_city)
    {
        $this->container['recipient_city'] = $recipient_city;

        return $this;
    }

    /**
     * Gets recipient_address
     *
     * @return string
     */
    public function getRecipientAddress()
    {
        return $this->container['recipient_address'];
    }

    /**
     * Sets recipient_address
     *
     * @param string $recipient_address recipient_address
     *
     * @return $this
     */
    public function setRecipientAddress($recipient_address)
    {
        $this->container['recipient_address'] = $recipient_address;

        return $this;
    }

    /**
     * Gets recipient_region
     *
     * @return string
     */
    public function getRecipientRegion()
    {
        return $this->container['recipient_region'];
    }

    /**
     * Sets recipient_region
     *
     * @param string $recipient_region recipient_region
     *
     * @return $this
     */
    public function setRecipientRegion($recipient_region)
    {
        $this->container['recipient_region'] = $recipient_region;

        return $this;
    }

    /**
     * Gets building_name
     *
     * @return string
     */
    public function getBuildingName()
    {
        return $this->container['building_name'];
    }

    /**
     * Sets building_name
     *
     * @param string $building_name building_name
     *
     * @return $this
     */
    public function setBuildingName($building_name)
    {
        $this->container['building_name'] = $building_name;

        return $this;
    }

    /**
     * Gets instructions
     *
     * @return string
     */
    public function getInstructions()
    {
        return $this->container['instructions'];
    }

    /**
     * Sets instructions
     *
     * @param string $instructions instructions
     *
     * @return $this
     */
    public function setInstructions($instructions)
    {
        $this->container['instructions'] = $instructions;

        return $this;
    }

    /**
     * Gets prefecture
     *
     * @return string
     */
    public function getPrefecture()
    {
        return $this->container['prefecture'];
    }

    /**
     * Sets prefecture
     *
     * @param string $prefecture prefecture
     *
     * @return $this
     */
    public function setPrefecture($prefecture)
    {
        $this->container['prefecture'] = $prefecture;

        return $this;
    }

    /**
     * Gets prefecture_en
     *
     * @return string
     */
    public function getPrefectureEn()
    {
        return $this->container['prefecture_en'];
    }

    /**
     * Sets prefecture_en
     *
     * @param string $prefecture_en prefecture_en
     *
     * @return $this
     */
    public function setPrefectureEn($prefecture_en)
    {
        $this->container['prefecture_en'] = $prefecture_en;

        return $this;
    }

    /**
     * Gets recipient_city_en
     *
     * @return string
     */
    public function getRecipientCityEn()
    {
        return $this->container['recipient_city_en'];
    }

    /**
     * Sets recipient_city_en
     *
     * @param string $recipient_city_en recipient_city_en
     *
     * @return $this
     */
    public function setRecipientCityEn($recipient_city_en)
    {
        $this->container['recipient_city_en'] = $recipient_city_en;

        return $this;
    }

    /**
     * Gets recipient_address_en
     *
     * @return string
     */
    public function getRecipientAddressEn()
    {
        return $this->container['recipient_address_en'];
    }

    /**
     * Sets recipient_address_en
     *
     * @param string $recipient_address_en recipient_address_en
     *
     * @return $this
     */
    public function setRecipientAddressEn($recipient_address_en)
    {
        $this->container['recipient_address_en'] = $recipient_address_en;

        return $this;
    }

    /**
     * Gets florist_country
     *
     * @return string
     */
    public function getFloristCountry()
    {
        return $this->container['florist_country'];
    }

    /**
     * Sets florist_country
     *
     * @param string $florist_country florist_country
     *
     * @return $this
     */
    public function setFloristCountry($florist_country)
    {
        $this->container['florist_country'] = $florist_country;

        return $this;
    }

    /**
     * Gets florist_member_code
     *
     * @return string
     */
    public function getFloristMemberCode()
    {
        return $this->container['florist_member_code'];
    }

    /**
     * Sets florist_member_code
     *
     * @param string $florist_member_code florist_member_code
     *
     * @return $this
     */
    public function setFloristMemberCode($florist_member_code)
    {
        $this->container['florist_member_code'] = $florist_member_code;

        return $this;
    }

    /**
     * Gets florist_location
     *
     * @return string
     */
    public function getFloristLocation()
    {
        return $this->container['florist_location'];
    }

    /**
     * Sets florist_location
     *
     * @param string $florist_location florist_location
     *
     * @return $this
     */
    public function setFloristLocation($florist_location)
    {
        $this->container['florist_location'] = $florist_location;

        return $this;
    }

    /**
     * Gets florist_name
     *
     * @return string
     */
    public function getFloristName()
    {
        return $this->container['florist_name'];
    }

    /**
     * Sets florist_name
     *
     * @param string $florist_name florist_name
     *
     * @return $this
     */
    public function setFloristName($florist_name)
    {
        $this->container['florist_name'] = $florist_name;

        return $this;
    }

    /**
     * Gets recipient_tele_home_part1
     *
     * @return string
     */
    public function getRecipientTeleHomePart1()
    {
        return $this->container['recipient_tele_home_part1'];
    }

    /**
     * Sets recipient_tele_home_part1
     *
     * @param string $recipient_tele_home_part1 recipient_tele_home_part1
     *
     * @return $this
     */
    public function setRecipientTeleHomePart1($recipient_tele_home_part1)
    {
        $this->container['recipient_tele_home_part1'] = $recipient_tele_home_part1;

        return $this;
    }

    /**
     * Gets recipient_tele_home_part2
     *
     * @return string
     */
    public function getRecipientTeleHomePart2()
    {
        return $this->container['recipient_tele_home_part2'];
    }

    /**
     * Sets recipient_tele_home_part2
     *
     * @param string $recipient_tele_home_part2 recipient_tele_home_part2
     *
     * @return $this
     */
    public function setRecipientTeleHomePart2($recipient_tele_home_part2)
    {
        $this->container['recipient_tele_home_part2'] = $recipient_tele_home_part2;

        return $this;
    }

    /**
     * Gets recipient_tele_home_part3
     *
     * @return string
     */
    public function getRecipientTeleHomePart3()
    {
        return $this->container['recipient_tele_home_part3'];
    }

    /**
     * Sets recipient_tele_home_part3
     *
     * @param string $recipient_tele_home_part3 recipient_tele_home_part3
     *
     * @return $this
     */
    public function setRecipientTeleHomePart3($recipient_tele_home_part3)
    {
        $this->container['recipient_tele_home_part3'] = $recipient_tele_home_part3;

        return $this;
    }

    /**
     * Gets recipient_tele_work_part1
     *
     * @return string
     */
    public function getRecipientTeleWorkPart1()
    {
        return $this->container['recipient_tele_work_part1'];
    }

    /**
     * Sets recipient_tele_work_part1
     *
     * @param string $recipient_tele_work_part1 recipient_tele_work_part1
     *
     * @return $this
     */
    public function setRecipientTeleWorkPart1($recipient_tele_work_part1)
    {
        $this->container['recipient_tele_work_part1'] = $recipient_tele_work_part1;

        return $this;
    }

    /**
     * Gets recipient_tele_work_part2
     *
     * @return string
     */
    public function getRecipientTeleWorkPart2()
    {
        return $this->container['recipient_tele_work_part2'];
    }

    /**
     * Sets recipient_tele_work_part2
     *
     * @param string $recipient_tele_work_part2 recipient_tele_work_part2
     *
     * @return $this
     */
    public function setRecipientTeleWorkPart2($recipient_tele_work_part2)
    {
        $this->container['recipient_tele_work_part2'] = $recipient_tele_work_part2;

        return $this;
    }

    /**
     * Gets recipient_tele_work_part3
     *
     * @return string
     */
    public function getRecipientTeleWorkPart3()
    {
        return $this->container['recipient_tele_work_part3'];
    }

    /**
     * Sets recipient_tele_work_part3
     *
     * @param string $recipient_tele_work_part3 recipient_tele_work_part3
     *
     * @return $this
     */
    public function setRecipientTeleWorkPart3($recipient_tele_work_part3)
    {
        $this->container['recipient_tele_work_part3'] = $recipient_tele_work_part3;

        return $this;
    }

    /**
     * Gets delivery_time_from
     *
     * @return string
     */
    public function getDeliveryTimeFrom()
    {
        return $this->container['delivery_time_from'];
    }

    /**
     * Sets delivery_time_from
     *
     * @param string $delivery_time_from delivery_time_from
     *
     * @return $this
     */
    public function setDeliveryTimeFrom($delivery_time_from)
    {
        $this->container['delivery_time_from'] = $delivery_time_from;

        return $this;
    }

    /**
     * Gets delivery_time_to
     *
     * @return string
     */
    public function getDeliveryTimeTo()
    {
        return $this->container['delivery_time_to'];
    }

    /**
     * Sets delivery_time_to
     *
     * @param string $delivery_time_to delivery_time_to
     *
     * @return $this
     */
    public function setDeliveryTimeTo($delivery_time_to)
    {
        $this->container['delivery_time_to'] = $delivery_time_to;

        return $this;
    }

    /**
     * Gets delivery_date_from
     *
     * @return \DateTime
     */
    public function getDeliveryDateFrom()
    {
        return $this->container['delivery_date_from'];
    }

    /**
     * Sets delivery_date_from
     *
     * @param \DateTime $delivery_date_from delivery_date_from
     *
     * @return $this
     */
    public function setDeliveryDateFrom($delivery_date_from)
    {
        $this->container['delivery_date_from'] = $delivery_date_from;

        return $this;
    }

    /**
     * Gets delivery_date_to
     *
     * @return \DateTime
     */
    public function getDeliveryDateTo()
    {
        return $this->container['delivery_date_to'];
    }

    /**
     * Sets delivery_date_to
     *
     * @param \DateTime $delivery_date_to delivery_date_to
     *
     * @return $this
     */
    public function setDeliveryDateTo($delivery_date_to)
    {
        $this->container['delivery_date_to'] = $delivery_date_to;

        return $this;
    }

    /**
     * Gets occasion
     *
     * @return string
     */
    public function getOccasion()
    {
        return $this->container['occasion'];
    }

    /**
     * Sets occasion
     *
     * @param string $occasion occasion
     *
     * @return $this
     */
    public function setOccasion($occasion)
    {
        $this->container['occasion'] = $occasion;

        return $this;
    }

    /**
     * Gets delivery
     *
     * @return string
     */
    public function getDelivery()
    {
        return $this->container['delivery'];
    }

    /**
     * Sets delivery
     *
     * @param string $delivery delivery
     *
     * @return $this
     */
    public function setDelivery($delivery)
    {
        $this->container['delivery'] = $delivery;

        return $this;
    }

    /**
     * Gets total_price
     *
     * @return double
     */
    public function getTotalPrice()
    {
        return $this->container['total_price'];
    }

    /**
     * Sets total_price
     *
     * @param double $total_price total_price
     *
     * @return $this
     */
    public function setTotalPrice($total_price)
    {
        $this->container['total_price'] = $total_price;

        return $this;
    }

    /**
     * Gets sender_name
     *
     * @return string
     */
    public function getSenderName()
    {
        return $this->container['sender_name'];
    }

    /**
     * Sets sender_name
     *
     * @param string $sender_name sender_name
     *
     * @return $this
     */
    public function setSenderName($sender_name)
    {
        $this->container['sender_name'] = $sender_name;

        return $this;
    }

    /**
     * Gets sender_country
     *
     * @return string
     */
    public function getSenderCountry()
    {
        return $this->container['sender_country'];
    }

    /**
     * Sets sender_country
     *
     * @param string $sender_country sender_country
     *
     * @return $this
     */
    public function setSenderCountry($sender_country)
    {
        $this->container['sender_country'] = $sender_country;

        return $this;
    }

    /**
     * Gets sender_post_code
     *
     * @return string
     */
    public function getSenderPostCode()
    {
        return $this->container['sender_post_code'];
    }

    /**
     * Sets sender_post_code
     *
     * @param string $sender_post_code sender_post_code
     *
     * @return $this
     */
    public function setSenderPostCode($sender_post_code)
    {
        $this->container['sender_post_code'] = $sender_post_code;

        return $this;
    }

    /**
     * Gets sender_address
     *
     * @return string
     */
    public function getSenderAddress()
    {
        return $this->container['sender_address'];
    }

    /**
     * Sets sender_address
     *
     * @param string $sender_address sender_address
     *
     * @return $this
     */
    public function setSenderAddress($sender_address)
    {
        $this->container['sender_address'] = $sender_address;

        return $this;
    }

    /**
     * Gets sender_city
     *
     * @return string
     */
    public function getSenderCity()
    {
        return $this->container['sender_city'];
    }

    /**
     * Sets sender_city
     *
     * @param string $sender_city sender_city
     *
     * @return $this
     */
    public function setSenderCity($sender_city)
    {
        $this->container['sender_city'] = $sender_city;

        return $this;
    }

    /**
     * Gets sender_region
     *
     * @return string
     */
    public function getSenderRegion()
    {
        return $this->container['sender_region'];
    }

    /**
     * Sets sender_region
     *
     * @param string $sender_region sender_region
     *
     * @return $this
     */
    public function setSenderRegion($sender_region)
    {
        $this->container['sender_region'] = $sender_region;

        return $this;
    }

    /**
     * Gets sender_phone_home
     *
     * @return string
     */
    public function getSenderPhoneHome()
    {
        return $this->container['sender_phone_home'];
    }

    /**
     * Sets sender_phone_home
     *
     * @param string $sender_phone_home sender_phone_home
     *
     * @return $this
     */
    public function setSenderPhoneHome($sender_phone_home)
    {
        $this->container['sender_phone_home'] = $sender_phone_home;

        return $this;
    }

    /**
     * Gets sender_phone_work
     *
     * @return string
     */
    public function getSenderPhoneWork()
    {
        return $this->container['sender_phone_work'];
    }

    /**
     * Sets sender_phone_work
     *
     * @param string $sender_phone_work sender_phone_work
     *
     * @return $this
     */
    public function setSenderPhoneWork($sender_phone_work)
    {
        $this->container['sender_phone_work'] = $sender_phone_work;

        return $this;
    }

    /**
     * Gets sender_phone_mobile
     *
     * @return string
     */
    public function getSenderPhoneMobile()
    {
        return $this->container['sender_phone_mobile'];
    }

    /**
     * Sets sender_phone_mobile
     *
     * @param string $sender_phone_mobile sender_phone_mobile
     *
     * @return $this
     */
    public function setSenderPhoneMobile($sender_phone_mobile)
    {
        $this->container['sender_phone_mobile'] = $sender_phone_mobile;

        return $this;
    }

    /**
     * Gets senderemail
     *
     * @return string
     */
    public function getSenderemail()
    {
        return $this->container['senderemail'];
    }

    /**
     * Sets senderemail
     *
     * @param string $senderemail senderemail
     *
     * @return $this
     */
    public function setSenderemail($senderemail)
    {
        $this->container['senderemail'] = $senderemail;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    #[\ReturnTypeWillChange]
    public function offsetExists($offset)
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed
     */
    #[\ReturnTypeWillChange]
    public function offsetGet($offset)
    {
        return isset($this->container[$offset]) ? $this->container[$offset] : null;
    }

    /**
     * Sets value based on offset.
     *
     * @param integer $offset Offset
     * @param mixed   $value  Value to be set
     *
     * @return void
     */
    #[\ReturnTypeWillChange]
    public function offsetSet($offset, $value)
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    #[\ReturnTypeWillChange]
    public function offsetUnset($offset)
    {
        unset($this->container[$offset]);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        if (defined('JSON_PRETTY_PRINT')) { // use JSON pretty print
            return json_encode(
                ObjectSerializer::sanitizeForSerialization($this),
                JSON_PRETTY_PRINT
            );
        }

        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


