<?php
/**
 * QueryMessage
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.13
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace Swagger\Client\Model;

use \ArrayAccess;
use \Swagger\Client\ObjectSerializer;

/**
 * QueryMessage Class Doc Comment
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class QueryMessage implements ModelInterface, ArrayAccess
{
    const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $swaggerModelName = 'QueryMessage';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $swaggerTypes = [
        'subject' => 'string',
        'text' => 'string',
        'query_fields' => '\Swagger\Client\Model\QueryField[]',
        'floristgate_number' => 'int',
        'message_status' => 'int',
        'created_date' => '\DateTime',
        'modified_date' => '\DateTime',
        'confirmed_date' => '\DateTime',
        'from_unit_id' => 'int',
        'from_unit_message_id' => 'int',
        'to_unit_id' => 'int',
        'to_unit_message_id' => 'int',
        'operator' => 'string',
        'priority' => 'int'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $swaggerFormats = [
        'subject' => null,
        'text' => null,
        'query_fields' => null,
        'floristgate_number' => 'int32',
        'message_status' => 'int32',
        'created_date' => 'date-time',
        'modified_date' => 'date-time',
        'confirmed_date' => 'date-time',
        'from_unit_id' => 'int32',
        'from_unit_message_id' => 'int32',
        'to_unit_id' => 'int32',
        'to_unit_message_id' => 'int32',
        'operator' => null,
        'priority' => 'int32'
    ];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function swaggerTypes()
    {
        return self::$swaggerTypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function swaggerFormats()
    {
        return self::$swaggerFormats;
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'subject' => 'Subject',
        'text' => 'Text',
        'query_fields' => 'QueryFields',
        'floristgate_number' => 'FloristgateNumber',
        'message_status' => 'MessageStatus',
        'created_date' => 'CreatedDate',
        'modified_date' => 'ModifiedDate',
        'confirmed_date' => 'ConfirmedDate',
        'from_unit_id' => 'FromUnitID',
        'from_unit_message_id' => 'FromUnitMessageID',
        'to_unit_id' => 'ToUnitID',
        'to_unit_message_id' => 'ToUnitMessageID',
        'operator' => 'Operator',
        'priority' => 'Priority'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'subject' => 'setSubject',
        'text' => 'setText',
        'query_fields' => 'setQueryFields',
        'floristgate_number' => 'setFloristgateNumber',
        'message_status' => 'setMessageStatus',
        'created_date' => 'setCreatedDate',
        'modified_date' => 'setModifiedDate',
        'confirmed_date' => 'setConfirmedDate',
        'from_unit_id' => 'setFromUnitId',
        'from_unit_message_id' => 'setFromUnitMessageId',
        'to_unit_id' => 'setToUnitId',
        'to_unit_message_id' => 'setToUnitMessageId',
        'operator' => 'setOperator',
        'priority' => 'setPriority'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'subject' => 'getSubject',
        'text' => 'getText',
        'query_fields' => 'getQueryFields',
        'floristgate_number' => 'getFloristgateNumber',
        'message_status' => 'getMessageStatus',
        'created_date' => 'getCreatedDate',
        'modified_date' => 'getModifiedDate',
        'confirmed_date' => 'getConfirmedDate',
        'from_unit_id' => 'getFromUnitId',
        'from_unit_message_id' => 'getFromUnitMessageId',
        'to_unit_id' => 'getToUnitId',
        'to_unit_message_id' => 'getToUnitMessageId',
        'operator' => 'getOperator',
        'priority' => 'getPriority'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$swaggerModelName;
    }

    const MESSAGE_STATUS_1 = 1;
    const MESSAGE_STATUS_2 = 2;
    const MESSAGE_STATUS_3 = 3;
    const PRIORITY_1 = 1;
    const PRIORITY_2 = 2;
    const PRIORITY_3 = 3;
    

    
    /**
     * Gets allowable values of the enum
     *
     * @return string[]
     */
    public function getMessageStatusAllowableValues()
    {
        return [
            self::MESSAGE_STATUS_1,
            self::MESSAGE_STATUS_2,
            self::MESSAGE_STATUS_3,
        ];
    }
    
    /**
     * Gets allowable values of the enum
     *
     * @return string[]
     */
    public function getPriorityAllowableValues()
    {
        return [
            self::PRIORITY_1,
            self::PRIORITY_2,
            self::PRIORITY_3,
        ];
    }
    

    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->container['subject'] = isset($data['subject']) ? $data['subject'] : null;
        $this->container['text'] = isset($data['text']) ? $data['text'] : null;
        $this->container['query_fields'] = isset($data['query_fields']) ? $data['query_fields'] : null;
        $this->container['floristgate_number'] = isset($data['floristgate_number']) ? $data['floristgate_number'] : null;
        $this->container['message_status'] = isset($data['message_status']) ? $data['message_status'] : null;
        $this->container['created_date'] = isset($data['created_date']) ? $data['created_date'] : null;
        $this->container['modified_date'] = isset($data['modified_date']) ? $data['modified_date'] : null;
        $this->container['confirmed_date'] = isset($data['confirmed_date']) ? $data['confirmed_date'] : null;
        $this->container['from_unit_id'] = isset($data['from_unit_id']) ? $data['from_unit_id'] : null;
        $this->container['from_unit_message_id'] = isset($data['from_unit_message_id']) ? $data['from_unit_message_id'] : null;
        $this->container['to_unit_id'] = isset($data['to_unit_id']) ? $data['to_unit_id'] : null;
        $this->container['to_unit_message_id'] = isset($data['to_unit_message_id']) ? $data['to_unit_message_id'] : null;
        $this->container['operator'] = isset($data['operator']) ? $data['operator'] : null;
        $this->container['priority'] = isset($data['priority']) ? $data['priority'] : null;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        $allowedValues = $this->getMessageStatusAllowableValues();
        if (!is_null($this->container['message_status']) && !in_array($this->container['message_status'], $allowedValues, true)) {
            $invalidProperties[] = sprintf(
                "invalid value for 'message_status', must be one of '%s'",
                implode("', '", $allowedValues)
            );
        }

        $allowedValues = $this->getPriorityAllowableValues();
        if (!is_null($this->container['priority']) && !in_array($this->container['priority'], $allowedValues, true)) {
            $invalidProperties[] = sprintf(
                "invalid value for 'priority', must be one of '%s'",
                implode("', '", $allowedValues)
            );
        }

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets subject
     *
     * @return string
     */
    public function getSubject()
    {
        return $this->container['subject'];
    }

    /**
     * Sets subject
     *
     * @param string $subject subject
     *
     * @return $this
     */
    public function setSubject($subject)
    {
        $this->container['subject'] = $subject;

        return $this;
    }

    /**
     * Gets text
     *
     * @return string
     */
    public function getText()
    {
        return $this->container['text'];
    }

    /**
     * Sets text
     *
     * @param string $text text
     *
     * @return $this
     */
    public function setText($text)
    {
        $this->container['text'] = $text;

        return $this;
    }

    /**
     * Gets query_fields
     *
     * @return \Swagger\Client\Model\QueryField[]
     */
    public function getQueryFields()
    {
        return $this->container['query_fields'];
    }

    /**
     * Sets query_fields
     *
     * @param \Swagger\Client\Model\QueryField[] $query_fields query_fields
     *
     * @return $this
     */
    public function setQueryFields($query_fields)
    {
        $this->container['query_fields'] = $query_fields;

        return $this;
    }

    /**
     * Gets floristgate_number
     *
     * @return int
     */
    public function getFloristgateNumber()
    {
        return $this->container['floristgate_number'];
    }

    /**
     * Sets floristgate_number
     *
     * @param int $floristgate_number floristgate_number
     *
     * @return $this
     */
    public function setFloristgateNumber($floristgate_number)
    {
        $this->container['floristgate_number'] = $floristgate_number;

        return $this;
    }

    /**
     * Gets message_status
     *
     * @return int
     */
    public function getMessageStatus()
    {
        return $this->container['message_status'];
    }

    /**
     * Sets message_status
     *
     * @param int $message_status message_status
     *
     * @return $this
     */
    public function setMessageStatus($message_status)
    {
        $allowedValues = $this->getMessageStatusAllowableValues();
        if (!is_null($message_status) && !in_array($message_status, $allowedValues, true)) {
            throw new \InvalidArgumentException(
                sprintf(
                    "Invalid value for 'message_status', must be one of '%s'",
                    implode("', '", $allowedValues)
                )
            );
        }
        $this->container['message_status'] = $message_status;

        return $this;
    }

    /**
     * Gets created_date
     *
     * @return \DateTime
     */
    public function getCreatedDate()
    {
        return $this->container['created_date'];
    }

    /**
     * Sets created_date
     *
     * @param \DateTime $created_date created_date
     *
     * @return $this
     */
    public function setCreatedDate($created_date)
    {
        $this->container['created_date'] = $created_date;

        return $this;
    }

    /**
     * Gets modified_date
     *
     * @return \DateTime
     */
    public function getModifiedDate()
    {
        return $this->container['modified_date'];
    }

    /**
     * Sets modified_date
     *
     * @param \DateTime $modified_date modified_date
     *
     * @return $this
     */
    public function setModifiedDate($modified_date)
    {
        $this->container['modified_date'] = $modified_date;

        return $this;
    }

    /**
     * Gets confirmed_date
     *
     * @return \DateTime
     */
    public function getConfirmedDate()
    {
        return $this->container['confirmed_date'];
    }

    /**
     * Sets confirmed_date
     *
     * @param \DateTime $confirmed_date confirmed_date
     *
     * @return $this
     */
    public function setConfirmedDate($confirmed_date)
    {
        $this->container['confirmed_date'] = $confirmed_date;

        return $this;
    }

    /**
     * Gets from_unit_id
     *
     * @return int
     */
    public function getFromUnitId()
    {
        return $this->container['from_unit_id'];
    }

    /**
     * Sets from_unit_id
     *
     * @param int $from_unit_id from_unit_id
     *
     * @return $this
     */
    public function setFromUnitId($from_unit_id)
    {
        $this->container['from_unit_id'] = $from_unit_id;

        return $this;
    }

    /**
     * Gets from_unit_message_id
     *
     * @return int
     */
    public function getFromUnitMessageId()
    {
        return $this->container['from_unit_message_id'];
    }

    /**
     * Sets from_unit_message_id
     *
     * @param int $from_unit_message_id from_unit_message_id
     *
     * @return $this
     */
    public function setFromUnitMessageId($from_unit_message_id)
    {
        $this->container['from_unit_message_id'] = $from_unit_message_id;

        return $this;
    }

    /**
     * Gets to_unit_id
     *
     * @return int
     */
    public function getToUnitId()
    {
        return $this->container['to_unit_id'];
    }

    /**
     * Sets to_unit_id
     *
     * @param int $to_unit_id to_unit_id
     *
     * @return $this
     */
    public function setToUnitId($to_unit_id)
    {
        $this->container['to_unit_id'] = $to_unit_id;

        return $this;
    }

    /**
     * Gets to_unit_message_id
     *
     * @return int
     */
    public function getToUnitMessageId()
    {
        return $this->container['to_unit_message_id'];
    }

    /**
     * Sets to_unit_message_id
     *
     * @param int $to_unit_message_id to_unit_message_id
     *
     * @return $this
     */
    public function setToUnitMessageId($to_unit_message_id)
    {
        $this->container['to_unit_message_id'] = $to_unit_message_id;

        return $this;
    }

    /**
     * Gets operator
     *
     * @return string
     */
    public function getOperator()
    {
        return $this->container['operator'];
    }

    /**
     * Sets operator
     *
     * @param string $operator operator
     *
     * @return $this
     */
    public function setOperator($operator)
    {
        $this->container['operator'] = $operator;

        return $this;
    }

    /**
     * Gets priority
     *
     * @return int
     */
    public function getPriority()
    {
        return $this->container['priority'];
    }

    /**
     * Sets priority
     *
     * @param int $priority priority
     *
     * @return $this
     */
    public function setPriority($priority)
    {
        $allowedValues = $this->getPriorityAllowableValues();
        if (!is_null($priority) && !in_array($priority, $allowedValues, true)) {
            throw new \InvalidArgumentException(
                sprintf(
                    "Invalid value for 'priority', must be one of '%s'",
                    implode("', '", $allowedValues)
                )
            );
        }
        $this->container['priority'] = $priority;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset)
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed
     */
    public function offsetGet($offset)
    {
        return isset($this->container[$offset]) ? $this->container[$offset] : null;
    }

    /**
     * Sets value based on offset.
     *
     * @param integer $offset Offset
     * @param mixed   $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value)
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset)
    {
        unset($this->container[$offset]);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        if (defined('JSON_PRETTY_PRINT')) { // use JSON pretty print
            return json_encode(
                ObjectSerializer::sanitizeForSerialization($this),
                JSON_PRETTY_PRINT
            );
        }

        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


