<?php
/**
 * APIEntitiesMessagesOrderTranslationTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Swan API v4
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v4
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.43
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * APIEntitiesMessagesOrderTranslationTest Class Doc Comment
 *
 * @category    Class
 * @description APIEntitiesMessagesOrderTranslation
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class APIEntitiesMessagesOrderTranslationTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "APIEntitiesMessagesOrderTranslation"
     */
    public function testAPIEntitiesMessagesOrderTranslation()
    {
    }

    /**
     * Test attribute "id"
     */
    public function testPropertyId()
    {
    }

    /**
     * Test attribute "order_id"
     */
    public function testPropertyOrderId()
    {
    }

    /**
     * Test attribute "recipient_name"
     */
    public function testPropertyRecipientName()
    {
    }

    /**
     * Test attribute "recipient_postal_code"
     */
    public function testPropertyRecipientPostalCode()
    {
    }

    /**
     * Test attribute "recipient_city"
     */
    public function testPropertyRecipientCity()
    {
    }

    /**
     * Test attribute "recipient_address"
     */
    public function testPropertyRecipientAddress()
    {
    }

    /**
     * Test attribute "recipient_region"
     */
    public function testPropertyRecipientRegion()
    {
    }

    /**
     * Test attribute "building_name"
     */
    public function testPropertyBuildingName()
    {
    }

    /**
     * Test attribute "instructions"
     */
    public function testPropertyInstructions()
    {
    }

    /**
     * Test attribute "prefecture"
     */
    public function testPropertyPrefecture()
    {
    }

    /**
     * Test attribute "prefecture_en"
     */
    public function testPropertyPrefectureEn()
    {
    }

    /**
     * Test attribute "recipient_city_en"
     */
    public function testPropertyRecipientCityEn()
    {
    }

    /**
     * Test attribute "recipient_address_en"
     */
    public function testPropertyRecipientAddressEn()
    {
    }

    /**
     * Test attribute "florist_country"
     */
    public function testPropertyFloristCountry()
    {
    }

    /**
     * Test attribute "florist_member_code"
     */
    public function testPropertyFloristMemberCode()
    {
    }

    /**
     * Test attribute "florist_location"
     */
    public function testPropertyFloristLocation()
    {
    }

    /**
     * Test attribute "florist_name"
     */
    public function testPropertyFloristName()
    {
    }

    /**
     * Test attribute "recipient_tele_home_part1"
     */
    public function testPropertyRecipientTeleHomePart1()
    {
    }

    /**
     * Test attribute "recipient_tele_home_part2"
     */
    public function testPropertyRecipientTeleHomePart2()
    {
    }

    /**
     * Test attribute "recipient_tele_home_part3"
     */
    public function testPropertyRecipientTeleHomePart3()
    {
    }

    /**
     * Test attribute "recipient_tele_work_part1"
     */
    public function testPropertyRecipientTeleWorkPart1()
    {
    }

    /**
     * Test attribute "recipient_tele_work_part2"
     */
    public function testPropertyRecipientTeleWorkPart2()
    {
    }

    /**
     * Test attribute "recipient_tele_work_part3"
     */
    public function testPropertyRecipientTeleWorkPart3()
    {
    }

    /**
     * Test attribute "delivery_time_from"
     */
    public function testPropertyDeliveryTimeFrom()
    {
    }

    /**
     * Test attribute "delivery_time_to"
     */
    public function testPropertyDeliveryTimeTo()
    {
    }

    /**
     * Test attribute "delivery_date_from"
     */
    public function testPropertyDeliveryDateFrom()
    {
    }

    /**
     * Test attribute "delivery_date_to"
     */
    public function testPropertyDeliveryDateTo()
    {
    }

    /**
     * Test attribute "occasion"
     */
    public function testPropertyOccasion()
    {
    }

    /**
     * Test attribute "delivery"
     */
    public function testPropertyDelivery()
    {
    }

    /**
     * Test attribute "total_price"
     */
    public function testPropertyTotalPrice()
    {
    }

    /**
     * Test attribute "sender_name"
     */
    public function testPropertySenderName()
    {
    }

    /**
     * Test attribute "sender_country"
     */
    public function testPropertySenderCountry()
    {
    }

    /**
     * Test attribute "sender_post_code"
     */
    public function testPropertySenderPostCode()
    {
    }

    /**
     * Test attribute "sender_address"
     */
    public function testPropertySenderAddress()
    {
    }

    /**
     * Test attribute "sender_city"
     */
    public function testPropertySenderCity()
    {
    }

    /**
     * Test attribute "sender_region"
     */
    public function testPropertySenderRegion()
    {
    }

    /**
     * Test attribute "sender_phone_home"
     */
    public function testPropertySenderPhoneHome()
    {
    }

    /**
     * Test attribute "sender_phone_work"
     */
    public function testPropertySenderPhoneWork()
    {
    }

    /**
     * Test attribute "sender_phone_mobile"
     */
    public function testPropertySenderPhoneMobile()
    {
    }

    /**
     * Test attribute "senderemail"
     */
    public function testPropertySenderemail()
    {
    }
}
