<?php
/**
 * ModelMessagesMessageContainerExtendedTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Swan API v4
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v4
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.43
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * ModelMessagesMessageContainerExtendedTest Class Doc Comment
 *
 * @category    Class
 * @description ModelMessagesMessageContainerExtended
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class ModelMessagesMessageContainerExtendedTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "ModelMessagesMessageContainerExtended"
     */
    public function testModelMessagesMessageContainerExtended()
    {
    }

    /**
     * Test attribute "count"
     */
    public function testPropertyCount()
    {
    }

    /**
     * Test attribute "backcharge_cleared_messages"
     */
    public function testPropertyBackchargeClearedMessages()
    {
    }

    /**
     * Test attribute "backcharge_confirmed_messages"
     */
    public function testPropertyBackchargeConfirmedMessages()
    {
    }

    /**
     * Test attribute "backcharge_denied_messages"
     */
    public function testPropertyBackchargeDeniedMessages()
    {
    }

    /**
     * Test attribute "backcharge_messages"
     */
    public function testPropertyBackchargeMessages()
    {
    }

    /**
     * Test attribute "florist_assigned_messages"
     */
    public function testPropertyFloristAssignedMessages()
    {
    }

    /**
     * Test attribute "delivery_confirmed_messages"
     */
    public function testPropertyDeliveryConfirmedMessages()
    {
    }

    /**
     * Test attribute "general_messages"
     */
    public function testPropertyGeneralMessages()
    {
    }

    /**
     * Test attribute "order_cancellation_confirmed_messages"
     */
    public function testPropertyOrderCancellationConfirmedMessages()
    {
    }

    /**
     * Test attribute "order_cancellation_denied_messages"
     */
    public function testPropertyOrderCancellationDeniedMessages()
    {
    }

    /**
     * Test attribute "order_cancellation_messages"
     */
    public function testPropertyOrderCancellationMessages()
    {
    }

    /**
     * Test attribute "order_cleared_messages"
     */
    public function testPropertyOrderClearedMessages()
    {
    }

    /**
     * Test attribute "order_messages"
     */
    public function testPropertyOrderMessages()
    {
    }

    /**
     * Test attribute "order_rejected_messages"
     */
    public function testPropertyOrderRejectedMessages()
    {
    }

    /**
     * Test attribute "query_messages"
     */
    public function testPropertyQueryMessages()
    {
    }
}
