<?php
/**
 * ModelProductCategoryTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Swan API v4
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v4
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.43
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * ModelProductCategoryTest Class Doc Comment
 *
 * @category    Class
 * @description ModelProductCategory
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class ModelProductCategoryTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "ModelProductCategory"
     */
    public function testModelProductCategory()
    {
    }

    /**
     * Test attribute "id"
     */
    public function testPropertyId()
    {
    }

    /**
     * Test attribute "name"
     */
    public function testPropertyName()
    {
    }

    /**
     * Test attribute "description"
     */
    public function testPropertyDescription()
    {
    }

    /**
     * Test attribute "parent_id"
     */
    public function testPropertyParentId()
    {
    }

    /**
     * Test attribute "ordering"
     */
    public function testPropertyOrdering()
    {
    }

    /**
     * Test attribute "removed_date"
     */
    public function testPropertyRemovedDate()
    {
    }

    /**
     * Test attribute "last_update"
     */
    public function testPropertyLastUpdate()
    {
    }

    /**
     * Test attribute "allow_children"
     */
    public function testPropertyAllowChildren()
    {
    }

    /**
     * Test attribute "allow_select_many"
     */
    public function testPropertyAllowSelectMany()
    {
    }

    /**
     * Test attribute "is_addon"
     */
    public function testPropertyIsAddon()
    {
    }

    /**
     * Test attribute "allow_addon"
     */
    public function testPropertyAllowAddon()
    {
    }

    /**
     * Test attribute "generic"
     */
    public function testPropertyGeneric()
    {
    }

    /**
     * Test attribute "non_generic"
     */
    public function testPropertyNonGeneric()
    {
    }
}
