<?php
/**
 * CountryInfoTextApiTest
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.13
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace Swagger\Client;

use \Swagger\Client\Configuration;
use \Swagger\Client\ApiException;
use \Swagger\Client\ObjectSerializer;

/**
 * CountryInfoTextApiTest Class Doc Comment
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class CountryInfoTextApiTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test case for countryInfoTextGetTranslatedCountryInfoTexts
     *
     * Get translated country info texts for one country..
     *
     */
    public function testCountryInfoTextGetTranslatedCountryInfoTexts()
    {
    }

    /**
     * Test case for countryInfoTextGetTranslatedCountryInfoTextsByType
     *
     * Get the translated country info text for one country of requested info text type..
     *
     */
    public function testCountryInfoTextGetTranslatedCountryInfoTextsByType()
    {
    }

    /**
     * Test case for countryInfoTextReplaceCountryInfoTexts
     *
     * Replace translated country info texts..
     *
     */
    public function testCountryInfoTextReplaceCountryInfoTexts()
    {
    }

    /**
     * Test case for countryInfoTextSaveCountryInfoText
     *
     * Update or save a single translated country info text by country and type, leaving other types of same country untouched..
     *
     */
    public function testCountryInfoTextSaveCountryInfoText()
    {
    }
}
