<?php
/**
 * ProductApiTest
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Swan API v4
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v4
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.43
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace Swagger\Client;

use \Swagger\Client\Configuration;
use \Swagger\Client\ApiException;
use \Swagger\Client\ObjectSerializer;

/**
 * ProductApiTest Class Doc Comment
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class ProductApiTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test case for productDelete
     *
     * Delete product.
     *
     */
    public function testProductDelete()
    {
    }

    /**
     * Test case for productGetAll
     *
     * Get all products.
     *
     */
    public function testProductGetAll()
    {
    }

    /**
     * Test case for productGetByCountry
     *
     * Get products of a country.
     *
     */
    public function testProductGetByCountry()
    {
    }

    /**
     * Test case for productGetById
     *
     * Get product by ID.
     *
     */
    public function testProductGetById()
    {
    }

    /**
     * Test case for productGetCreatedProducts
     *
     * Get created products by date.
     *
     */
    public function testProductGetCreatedProducts()
    {
    }

    /**
     * Test case for productGetCreatedProductsByCountry
     *
     * Get created products by date and country code.
     *
     */
    public function testProductGetCreatedProductsByCountry()
    {
    }

    /**
     * Test case for productGetDeletedProducts
     *
     * Get deleted products by date.
     *
     */
    public function testProductGetDeletedProducts()
    {
    }

    /**
     * Test case for productGetDeletedProductsByCountry
     *
     * Get deleted products by date and country code.
     *
     */
    public function testProductGetDeletedProductsByCountry()
    {
    }

    /**
     * Test case for productGetUpdatedProducts
     *
     * Get updated products by date.
     *
     */
    public function testProductGetUpdatedProducts()
    {
    }

    /**
     * Test case for productGetUpdatedProductsByCountry
     *
     * Get updated products by date and country code.
     *
     */
    public function testProductGetUpdatedProductsByCountry()
    {
    }

    /**
     * Test case for productGetWithAvailablePeriodsByCountry
     *
     * Get products with available periods of a country.
     *
     */
    public function testProductGetWithAvailablePeriodsByCountry()
    {
    }

    /**
     * Test case for productSave
     *
     * Create or update product.
     *
     */
    public function testProductSave()
    {
    }
}
